# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/addressbook/models/addressbook.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.people.models import people_pb2 as pb_dot_people_dot_models_dot_people__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/addressbook/models/addressbook.proto',
  package='pb.addressbook.models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\'pb/addressbook/models/addressbook.proto\x12\x15pb.addressbook.models\x1a\x1dpb/people/models/people.proto\"7\n\x0b\x41\x64\x64ressBook\x12(\n\x06people\x18\x01 \x03(\x0b\x32\x18.pb.people.models.Personb\x06proto3'
  ,
  dependencies=[pb_dot_people_dot_models_dot_people__pb2.DESCRIPTOR,])




_ADDRESSBOOK = _descriptor.Descriptor(
  name='AddressBook',
  full_name='pb.addressbook.models.AddressBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='pb.addressbook.models.AddressBook.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=152,
)

_ADDRESSBOOK.fields_by_name['people'].message_type = pb_dot_people_dot_models_dot_people__pb2._PERSON
DESCRIPTOR.message_types_by_name['AddressBook'] = _ADDRESSBOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressBook = _reflection.GeneratedProtocolMessageType('AddressBook', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSBOOK,
  '__module__' : 'pb.addressbook.models.addressbook_pb2'
  # @@protoc_insertion_point(class_scope:pb.addressbook.models.AddressBook)
  })
_sym_db.RegisterMessage(AddressBook)


# @@protoc_insertion_point(module_scope)
